on:
  push:
    paths-ignore:
      - '**/**.md'
      - 'docs/**'
env:
  SEMANTIC_VERSION: 0.1.${{github.run_number}}

concurrency: ci-${{ github.ref }}

name: sample-humanfriendlyid-csharp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{ env.SEMANTIC_VERSION }}
    - name: UnitTest
      run: dotnet test *.UnitTest --no-build --no-restore -c Release -p:Version=${{ env.SEMANTIC_VERSION }} --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory=testcoverage
      timeout-minutes: 10
    - name: Publish code coverage
      uses: codecov/codecov-action@v4
      with:
        root_dir: .
        fail_ci_if_error: true
        verbose: true
